### ISSUE TITLE
Apply patch

### ISSUE THREAD

**Issue by zaicopx** [aleigood/TrinityCore-Autobalance#1]
How to apply patch to trinitycore??
I use "patch -p1 < Autobalance.patch" and "git apply Autobalance.patch got error line 67

**Comment by zaicopx** [comment]
![IMG20200725202806.jpg](https://user-images.githubusercontent.com/68382531/88460507-ea6bc800-cec6-11ea-809d-2fe7099eae26.jpg)

**Comment by LEO33SoFo** [comment]
@zaicopx Try this one. It needs testing.
[mod-autobalance.patch](https://cdn.discordapp.com/attachments/291116559487991809/745088455482277939/mod-autobalance.patch)

Tested on https://github.com/TrinityCore/TrinityCore/commit/43986954fddc05e0fe1f225b0cf38a7b01f775bb.

**Comment by zaicopx** [comment]
> @zaicopx Try this one. It needs testing.
> [mod-autobalance.patch](https://cdn.discordapp.com/attachments/291116559487991809/745088455482277939/mod-autobalance.patch)
> 
> Tested on https://github.com/TrinityCore/TrinityCore/commit/43986954fddc05e0fe1f225b0cf38a7b01f775bb.

Thanks, I try it later

**Comment by sw586** [comment]
@zaicopx
I finally found you, friend, I want to study Raid-robot-for-TrinityCore with you, can you? I have added your friend

**Comment by zaicopx** [comment]
Yes I can apply this patch by manualy add in my source
