### ISSUE TITLE
Error on the chat when entering instances

### ISSUE THREAD

**Issue by LEO33SoFo** [aleigood/TrinityCore-Autobalance#2]
I get this error on the chat whenever I enter instances.
![Screenshot](https://cdn.discordapp.com/attachments/291116559487991809/745089262348927056/WoWScrnShot_081820_022214.png)

Using https://github.com/TrinityCore/TrinityCore/commit/43986954fddc05e0fe1f225b0cf38a7b01f775bb.

**Comment by aleigood** [comment]
Thanks for your feedback. It has been fixed.
